language: ruby
rvm:
  - ruby-head
  - 2.4
  - 2.2
  - 2.3
  - 2.1
  - 2.0
  - jruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
before_install:
  - sudo apt-get install libzbar-dev
