language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.7
  - 2.1.10
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
before_install:
  - sudo apt-get install libzbar-dev
